services:
  postgres:
    image: postgres:17-alpine
    env_file: ./pwa-backend/.env
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pswd
      POSTGRES_DB: db
    command: >
      postgres
      -c max_connections=50
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./pwa-backend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    env_file: ./pwa-backend/.env
    environment:
      NODE_ENV: development
      DEBUG: "app:*"
    volumes:
      - ./pwa-backend:/app
      - /app/node_modules
    depends_on:
      redis:
        condition: service_started

  frontend:
    build:
      context: ./pwa-frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    environment:
      REACT_APP_API_URL: "http://backend:3000"
    volumes:
      - ./pwa-frontend:/app_front
      - /app_front/node_modules
    stdin_open: true
    tty: true

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly no
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data

volumes:
  postgres_dev_data:
  redis_dev_data:
